name: Etude.ai
services:
  # ---------- BACKEND DATABASE ----------
  backend-db:
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d Etudeai " ]
      interval: 5s
      timeout: 3s
      retries: 20
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_DB: Etudeai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - backend_data:/data/postgres
      - ./ops/postgres/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - etudeai

#  # ---------- BACKEND SERVICE ----------
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: etudeai-backend
#    restart: always
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://backend-db:5432/etudeai
#      SPRING_DATASOURCE_USERNAME: etudeai
#      SPRING_DATASOURCE_PASSWORD: etudeai
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_PROFILES_ACTIVE: docker
#      KEYCLOAK_SERVER_URL: http://keycloak:8080
#      KEYCLOAK_REALM: etudeai
#      KEYCLOAK_CLIENT_ID: etudeai-backend
#    depends_on:
#      - backend-db
#      - keycloak
#    ports:
#      - "8081:8081"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak4
    command: [ "start-dev" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8080"
    volumes:
      - ./ops/keycloak/data:/opt/keycloak/data
      - ./ops/keycloak/themes:/opt/keycloak/themes
    networks:
      - etudeai

networks:
  etudeai:
    driver: bridge


volumes:
  backend_data:
