# Stage 1: Build the app using Maven image
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests -f /pom.xml

# Stage 2: Run the app using OpenJDK image
FROM eclipse-temurin:21-jdk
COPY --from=build /target/*.jar /app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]