server:
  port: 8081

spring:
  application:
    name: EtudeAI

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Etudeai
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/etudeAi

logging:
  level:
    org.springframework.security: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
