spring.application.name=EtudeAI
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/etudeai
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/etudeai/protocol/openid-connect/certs
